name: 'My Actions'
description: 'This action installs schemachange if it is not already installed and performs a dry run.'
runs:
  using: 'composite'
  steps:
    - name: Check if schemachange is installed and install if not
      run: |
        if ! command -v schemachange &> /dev/null
        then
            echo "schemachange is not installed. Installing..."
            if command -v pip &> /dev/null
            then
                pip install schemachange
            elif command -v pip3 &> /dev/null
            then
                pip3 install schemachange
            else
                echo "Neither pip nor pip3 found. Unable to install schemachange."
                exit 1
            fi
        else
            echo "schemachange is already installed."
        fi
      shell: bash

    - name: Perform dry run of schemachange
      run: |
        echo "Performing dry run of schemachange for user $SNOWFLAKE_USER..."

        for category in versioned repeatable always; do
          echo "Processing category: $category"
          for db_folder in ./instances/schemachange/scripts/$category/*; do
            if [ -d "$db_folder" ]; then
              db_name=$(basename "$db_folder")
              echo "Processing database folder: $db_name"
              for env in prod dev sit uat; do
                env_path=./instances/schemachange/config/$SNOWFLAKE_ENV/$env
                echo "Processing environment: $env_path"
                if [ -d "$env_path" ]; then
                  sub_env_path="$env_path/$db_name"
                  if [ -d "$sub_env_path" ]; then
                    sub_env_name=$(basename "$sub_env")
                    echo "Script Folder ($db_name) --> $db_folder"
                    echo "Config Folder ($sub_env_name) --> $sub_env_name"
                  fi
                fi
              done
            fi
          done
        done
      shell: bash
