name: 'My Actions'
description: 'This action installs schemachange if it is not already installed and performs a dry run.'
runs:
  using: 'composite'
  steps:
    - name: Check if schemachange is installed and install if not
      run: |
        if ! command -v schemachange &> /dev/null
        then
            echo "schemachange is not installed. Installing..."
            if command -v pip &> /dev/null
            then
                pip install schemachange
            elif command -v pip3 &> /dev/null
            then
                pip3 install schemachange
            else
                echo "Neither pip nor pip3 found. Unable to install schemachange."
                exit 1
            fi
        else
            echo "schemachange is already installed."
        fi
      shell: bash

    - name: Perform dry run of schemachange
      run: |
        for catagory in versioned repeatable always; do
          for db_folder in ./instances/schemachange/scripts/$catagory/*; do
            if [ -d "$db_folder" ]; then
               db_name=$(basename "$db_folder")
               for env in prod dev sit uat; do
                  for sub_env in ./instances/schemachange/config/$SNOWFLAKE_ENV/$env/*; do
                    if [ -d "$sub_env" ]; then
                      echo "Script Folder ($db_name) --> $db_folder"
                      echo "sub_env Folder ($sub_env) "
                    fi
                  done
               done
            fi
          done
        done
      shell: bash
