name: 'schemachange Action'
description: 'This action installs schemachange and prints the Snowflake user.'
inputs:
  name:
    description: 'Your name'
    required: true
    default: 'World'
  greeting:
    description: 'Greeting message'
    required: true
    default: 'Hello'
runs:
  using: 'node12'
  main: 'index.js'
env:
  SNOWFLAKE_USER: ${{ inputs.snowflake_user }}
