name: 'schemachange actions'
description: 'schemachange dry run     --> a) Check if schemachange is installed and install if not
                                           b) Perform dry run of schemachange
              schemachange auto commit --> a) Check if schemachange is installed and install if not
                                           b) Perform auto commit of schemachange'

runs:
  using: 'composite'
  steps:
      - name: Check if schemachange is installed and install if not
        run: |
          if ! command -v schemachange &> /dev/null
          then
              echo "schemachange is not installed. Installing..."
              if command -v pip &> /dev/null
              then
                  pip install schemachange
              elif command -v pip3 &> /dev/null
              then
                  pip3 install schemachange
              else
                  echo "Neither pip nor pip3 found. Unable to install schemachange."
                  exit 1
              fi
          else
              echo "schemachange is already installed."
          fi
        shell: bash

      - name: Perform dry run of schemachange
        if: github.workflow == 'schemachange dry run'
        run: |
          echo "Performing dry run of schemachange for user $SNOWFLAKE_USER..."

          for category in versioned repeatable always; do
            echo "Processing category: $category"
            for db_folder in ./instances/schemachange/scripts/$category/*; do
              if [ -d "$db_folder" ]; then
                db_name=$(basename "$db_folder")
                echo "Processing database folder: $db_name"
                echo "Script Folder: $db_folder"
                for env in prod dev sit uat; do
                  env_path=./instances/schemachange/config/$SNOWFLAKE_ENV/$db_name/$env
                  if [ -d "$env_path" ]; then
                    echo "Config Folder: $env_path"
                  fi
                done
              fi
            done
          done
        shell: bash


      - name: Perform deployment/auto commit of schemachange commands
        if: github.workflow != 'schemachange dry run'
        run: |
          echo "Performing Deployment"
        shell: bash
