name: Manual Dispatch and Actions Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'Sowmya'
      greeting:
        description: 'Greeting message'
        required: true
        default: 'Hello'

jobs:
  execute_actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Dry Run Action
        uses: ./.github/actions/schemachange
        with:
          name: ${{ github.event.inputs.name }}
          greeting: ${{ github.event.inputs.greeting }}
        env:
          SNOWFLAKE_USER: 'ssd'
          SNOWFLAKE_ENV:  'nonprod-us-eat-2'
