name: PRPRORPRO Dispatch and PR Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'
      greeting:
        description: 'Greeting message'
        required: true
        default: 'Hello'

  pull_request:
    branches:
      - ssd
    types: [opened, reopened]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Use Custom Action
        uses: ./.github/actions/schemachange/schema
        with:
          action: check_schemachange_installed
          name: ${{ github.event.inputs.name || 'World' }}
          greeting: ${{ github.event.inputs.greeting || 'Hello' }}
          snowflake_user: ddf
